### ISSUE TITLE
Unexpected string when importing the slider

### ISSUE THREAD

**Issue by Bobeta** [jechav/tiny-slider-react#3]
Tried with the sample code from the demo, but I get the following error:

**Uncaught SyntaxError: Unexpected string - commons.js:54025**
```
/***/ "./node_modules/ventura-slider/src/tiny-slider.module.js":
/***/ (function(module, exports) {

	// Format: ES MODULE
	// Version: 2.5.2

	// helper functions
	import './helpers/keys';
	import './helpers/childNode.remove';
```

**Comment by VilhelmNielsen** [comment]
@jechav The issue happens in this fork of tiny-slider that this package uses: https://github.com/jechav/tiny-slider

The newest version of `tiny-slider` seems to have fixed the issue, which could be related to missing `export` in `./helpers/keys`. The `./helpers/keys` looks to be inlined in the latest version of ´tiny-slider`.

@Bobeta Are you using SSR of some kind? I'm guessing the issue is Node.js or Webpack complaining about ES Modules.

**Comment by VilhelmNielsen** [comment]
@CyrilQuandalle I ended up writing my own wrapper for `tiny-slider`

**Comment by CyrilQuandalle** [comment]
Hi @VilhelmNielsen,
Thank you for your answer. On my side I ended up coding my own slider from scratch 😉

**Comment by Bobeta** [comment]
@VilhelmNielsen Could you share it with us? 👍

**Comment by VilhelmNielsen** [comment]
@Bobeta Here's a fairly simplified version, it should work: https://gist.github.com/VilhelmNielsen/2b87c4dd00b9e2e074ab346c2c2f80fb

**Comment by jplew** [comment]
@VilhelmNielsen's wrapper works well for me. The only way I could it to work server-side with Next.js was to import it dynamically though:

```
import dynamic from 'next/dynamic'

const Slider = dynamic(() => import('~/components/Slider'),
  {
    ssr: false,
  },
)
...

        <Slider>
          <img src="/static/image1.png" />
          <img src="/static/image2.png" />
          <img src="/static/image3.png" />
        </Slider>
```

**Comment by jechav** [comment]
@Bobeta Now the original library is compiled so shouldn't be any problem.
